### ISSUE TITLE
安装Liberty's Legacy Trainer和FusionFix后汉化失效

### ISSUE THREAD

**Issue by wb2324580** [GTAIV-Complete-Edition-text/feedback-IV.CHS#1]
操作过程：
----Steam下载游戏（完全版）；
----测试启动后正常；
----下载并覆盖汉化补丁；
----下载并覆盖FusionFix（使用的是赠品里提供的版本）；
----在nexusmods上下载安装Liberty's Legacy Trainer；
     ----按照上面教程，先按顺序安装Aru's ScriptHook
，ASI Loader
，Compatibility Patch for GTA IV: Complete Edition；
     ----再安装修改器本体；
----随后启动游戏，发现并没有汉化，遂删除目录下dsound.dll；
----再次启动游戏，仍没有汉化，但游戏可以正常进行，且修改器正常使用；
----尝试重新覆盖一次汉化，仍无效果；其他一切正常。

**Comment by wb2324580** [comment]
补充一句，我的系统使用了MacType，不知是否会有影响，谢谢！

**Comment by BlueNoBaka** [comment]
我这里复现不了，可以截图一下你的游戏根目录和plugins文件夹，发过来看看吗？
有必要的话，也可以先在纯净原版上只打汉化试试，看看是被其他Mod影响了还是另有原因。

**Comment by wb2324580** [comment]
目录如图，如果看不出问题所在，我再尝试纯净原版+汉化的组合，谢谢
![QQ截图20220615125551](https://user-images.githubusercontent.com/21260422/173739927-109488ed-8dd2-4c3b-b670-9c2e9a02e5cf.png)
![QQ截图20220615125622](https://user-images.githubusercontent.com/21260422/173739946-d89bd001-c561-462b-bd69-b529b9a0738c.png)
！

**Comment by BlueNoBaka** [comment]
按照你的目录放置了这些Mod，还是无法复现。(至少在我这里，这些Mod没有影响汉化补丁生效)
先禁用一下MacType试试吧，还是不行的话我也找不出原因了……

**Comment by wb2324580** [comment]
果然是MacType的问题...禁用后重启电脑再进入游戏汉化就能正常显示了。但神奇的是我重新开启MacType（注册表加载模式）并重启电脑后再次进入游戏，汉化此时还是正常可使用的，估计是成功注入过一次后就ok了，为保险起见我还是将GTAIV.exe加入到MacType的排除列表中。
是否可以理解为：首次安装汉化后，如果使用MacType，需要先禁用MacType使汉化成功运行一次，再根据需求重新开启MacType。

**Comment by BlueNoBaka** [comment]
看起来应该是这样？倒是没想到MacType也会有影响……
