### ISSUE TITLE
于英文前后添加半角空格以提高字幕可读性

### ISSUE THREAD

**Issue by HiRA017** [GTAIV-Complete-Edition-text/feedback-IV.CHS#11]
当前版本的汉化文本，汉字和英文人名、地名之间并无间距，经过 DirectWrite 或 GDI+ 渲染后的文本图像存在一定的可读性困扰。

可以考虑在汉字和英文之间键入空格，如：

1. “开到我们在Mohawk的地方去” → “开到我们在 Mohawk 的地方去”
2. “驾车前往Roman的住处” → “驾车前往 Roman 的住处”
3. ...

诸如此类，以此提高字幕可读性。

感谢汉化组的辛勤付出！

**Comment by BlueNoBaka** [comment]
我个人是没有中英混排加空格的习惯的，所以文本里也没基本加空格。(除了网页里的 `www.eunux.net`，这个当时特意加了)

文本打包工具一度有过自动加空格的功能，作为游戏内排版修好之前的过渡。但是会在所有全角字符和半角字符的交界处都加上空格，比如全角标点和英文之间、汉字和后面的 `... (三个英文句点)` 之间，就连 `~n~ (游戏内换行符)` 和后面的汉字之间都会加空格。  
后来程序那边修好了游戏内的排版 (主要是分词和自动换行)，就把这个功能从文本打包工具里删掉了。

不过那个版本的打包工具还在，我就自动加了下空格，然后一键替换了上面提到过的几个不太舒服的地方。  
网页文本的打包工具没加过这个功能，所以还是混排不带空格的状态。(部分网页的文本在游戏文本里，这部分会自动加空格)

还有一个上面没提到的副产物是 文本变色符 和 后面的汉字 之间也会加空格 (例："回到**船**上" → "回到 **船** 上")，效果也还好就不改了。

解压到游戏根目录替换普通的汉化文本即可。
[混排带空格的文本.zip](https://github.com/GTAIV-Complete-Edition-text/feedback-IV.CHS/files/9313159/default.zip)

**Comment by HiRA017** [comment]
非常感谢！
