### ISSUE TITLE
希望向下兼容1.0.8.0/1.1.3.0整合版本

### ISSUE THREAD

**Issue by ASC9S** [GTAIV-Complete-Edition-text/feedback-IV.CHS#12]
希望制作组给**1.0.8.0/1.1.3.0整合版本**适配汉化。我喜欢这个版本的原因是它同时支持[ZolikaPatch](https://gtaforums.com/topic/955449-iv-zolikapatch/)  + [FusionFix](https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/)模组，还有R*对之前版本的修复和**联机功能**。在使用[SteamAchievements.asi](https://gtaforums.com/topic/957432-steam-achievements-for-1070-1080/)之后依旧可以取得Steam成就。**感谢汉化组所有人的辛苦付出和努力**！

**Comment by BlueNoBaka** [comment]
开源的意思是想做的话可以**自己fork源代码做**，发布时**保留原名单**即可。
