### ISSUE TITLE
CWTDGen 字体修改工具需要更新

### ISSUE THREAD

**Issue by Corporation001** [GTAIV-Complete-Edition-text/feedback-IV.CHS#16]
在最新的 2023 年 7 月 4 日版汉化程序中文字位置好像有更动，使用目前的 CWTDGen 做新字体会发生文字乱码。

**Comment by ysc3839** [comment]
是否是先更新了汉化再使用CWTDGen生成贴图？工具是会读取游戏目录下 `plugins\GTA4.CHS\char_table.dat`，所以按理来说更新后是没问题的。

**Comment by Corporation001** [comment]
重新试一次可以了，谢谢。
