### ISSUE TITLE
使用CWTDGen修改TBoGT字体后，TBoGT无限载入

### ISSUE THREAD

**Issue by dhoiahdoishdoi** [GTAIV-Complete-Edition-text/feedback-IV.CHS#6]
TBoGT更换字体后游戏无限载入，用汉化自带字体可以正常游戏，但只更改GTA4和TLAD的字体的话TBoGT的中文会全部变成黑色字块

**Comment by BlueNoBaka** [comment]
- **TBoGT更换字体后游戏无限载入**
  通过 `CWTDGen (字库字体工具)` 复现成功，原因不明。
  暂时排除了贴图文件尺寸的因素，换用方正像素12生成的 `fonts.wtd` 只有886kb，TBoGT照样无限载入。
  但是用 `OpenIV` 导出 `CWTDGen` 生成的 `fonts.wtd` 中的 `font_chs`，再通过 `OpenIV` 将 `fonts.wtd` 中的 `font_chs` 替换为刚才导出的贴图并保存，即可正常进入TBoGT，此时 `fonts.wtd` 的大小为888kb。
  对TLAD进行相同的操作，`fonts.wtd` 的文件大小也会改变。
  我只能不负责任地猜测是字库工具生成TBoGT的字库时出了问题，具体还需要 @ysc3839 排查修复。

  暂时的解决方案：
  1. 下载安装 [OpenIV](https://openiv.com/)
  2. 启动 `OpenIV`，完成初次启动时需要进行的游戏路径选择
  3. 如有必要，可在 `Tools` - `Options...` - `Languages` 中将软件语言设置为中文
  4. 启动 `OpenIV` 后，勾选上方地址栏右侧的 `Edit Mode (编辑模式)`
  5. 通过 `OpenIV` 打开 `TBoGT\pc\textures\fonts.wtd`，选中里面的 `font_chs`
  6. 点击贴图编辑器左下角从左往右数第二个按钮，以 `.png` 格式导出该贴图
  7. 点击贴图编辑器右上角从左往右数第三个按钮，用上一步中导出的贴图替换 `font_chs`
  8. 点击贴图编辑器右下角从左往右数第一个按钮，保存
  9. 此时可以关闭贴图编辑器和 `OpenIV`，应该也可以正常进入TBoGT了


- **只更改GTA4和TLAD的字体的话TBoGT的中文会全部变成黑色字块**
  复现失败，猜测是和 Issue #4 类似的问题。

**Comment by dhoiahdoishdoi** [comment]
好的，谢谢

**Comment by ysc3839** [comment]
已经确认问题并修复了，本地测试是正常的，将在近期发布新版本。
或者也可以先用着测试版本 [CWTDGen-20200713-Testing.zip](https://github.com/GTAIV-Complete-Edition-text/feedback-IV.CHS/files/9096314/CWTDGen-20200713-Testing.zip)

**Comment by ysc3839** [comment]
对想要了解问题细节的人说：其实就是文件尺寸的问题，只不过从 `fonts.wtd` 的大小看不出来，因为数据是压缩过的。问题出在压缩前的数据，需要在末尾填充到一定大小，但是忘了，另外两个贴图文件恰好不需要填充，所以没有问题。

**Comment by ysc3839** [comment]
已更新正式版 https://github.com/GTAIV-Complete-Edition-text/CWTDGen/releases/tag/20220718
请帮忙测试是否还有问题，谢谢！

**Comment by dhoiahdoishdoi** [comment]
已经可以正常进入游戏了，谢谢
